name: Build mod JAR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Gradle CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle

    - name: Configure settings.gradle
      run: |
        cat << 'EOF' > settings.gradle
        pluginManagement {
          repositories {
            gradlePluginPortal()
            mavenCentral()
            maven { url = 'https://maven.neoforged.net/releases' }
          }
        }
        rootProject.name = 'MoCreaturesRemaster'
        EOF

    - name: Configure build.gradle
      run: |
        cat << 'EOF' > build.gradle
        plugins {
          id 'net.neoforged.gradle.userdev' version '7.0.145'
          id 'maven-publish'
        }

        group = 'com.example.mocreatures'
        version = '1.0.0'

        java {
          toolchain {
            languageVersion = JavaLanguageVersion.of(17)
          }
        }

        repositories {
          gradlePluginPortal()   // para idea-ext, UserDev, etc.
          mavenCentral()
          maven { url = 'https://maven.neoforged.net/releases' }
        }

        minecraft {
          mappings channel: 'official', version: '1.21.1'
          accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
        }

        dependencies {
          implementation 'net.neoforged:neoforge:20.3.21-beta'
        }

        tasks.jar {
          manifest {
            attributes(
              'Specification-Title': 'MoCreaturesRemaster',
              'Implementation-Version': version
            )
          }
        }
        EOF

    - name: Build JAR
      run: gradle clean build --no-daemon

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoCreaturesRemaster-1.21.1
        path: build/libs/MoCreaturesRemaster-1.21.1.jar
